// Auto-generated by make — do not edit
let buildVersion = "0.9.18"
let buildCommit = "bdef36d"
let buildBranch = "main"
let buildDate = "2026-04-12 11:34:36 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3"
